name: reinas_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.1
  bloc: any
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.19.0
  flutter_carousel_widget: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/candidatas/
    - assets/carrusel/